### ISSUE TITLE
Add Ability to Push MA Config Parameters in to Command Elements

### ISSUE THREAD

**Issue by bdesmond** [lithnet/ssh-managementagent#2]
It would be very helpful to be able to push the username and password config elements in to a <command> to reuse them. For example, something like this:

<command>someApp -u {sshma:username} -p {sshma:password} ...</command>

**Comment by ryannewington** [comment]
Hi Brian,

Try this

[Lithnet.SshMA.zip](https://github.com/lithnet/ssh-managementagent/files/559422/Lithnet.SshMA.zip)

Using the syntax you provided ( {sshma:username} ).

Fixes issue #1 as well.

Just delete lithnet.logging and renci.ssh DLLs and PDBs from your extensions folder before putting this new version in (they are compiled in the main dll now)

Let me know how it goes

Ryan

**Comment by bdesmond** [comment]
A refresh schema or editing the Connectivty page on the MA throws this error:

---

## Synchronization Service Manager

The configuration file could not be loaded
Exception has been thrown by the target of an invocation.

## No such attribute "sshma:username".

## OK

**Comment by ryannewington** [comment]
@bdesmond try this build

[Lithnet.SshMA.zip](https://github.com/lithnet/ssh-managementagent/files/567439/Lithnet.SshMA.zip)

**Comment by bdesmond** [comment]
Something is wrong with the zip - WinRAR and Windows Explorer both say it's corrupt

**Comment by ryannewington** [comment]
[Lithnet.SshMA.zip](https://github.com/lithnet/ssh-managementagent/files/573626/Lithnet.SshMA.zip)

Sorry @bdesmond, not sure what happened there. Try this one.

**Comment by ryannewington** [comment]
@bdesmond did this build do what you needed?
