### ISSUE TITLE
Add support for multiple attributes in an optional declaration section

### ISSUE THREAD

**Issue by aebenjam** [lithnet/ssh-managementagent#4]
We had the following command definitions for user object-operation-ExportAdd and object-operation-ExportModify, respectively:

`<command>/usr/bin/sudo /usr/sbin/useradd [-c "{comment},#{employeeID}#" ][-d {homeDirectory} ][-s {shell} ][-u {uid} ][-g {gid} ]{dn:$1}</command>`

`<command>/usr/bin/sudo /usr/sbin/usermod [-c "{comment},#{employeeID}#" ][-d {homeDirectory} ][-s {shell} ][-u {uid} ][-g {gid} ][-l {accountName} ]{dn:$1}</command>`

But, for a new user, it looks like the comment attribute was being substituted but not the employeeID.  And for a modify (updating the employeeID) it looks like the change to the employee wasn't being detected in terms of invoking the conditional "-c" option, and so the command was not executing with any options.  I'm inferring (possibly incorrectly?) that only substitution is happening per optional section.  Or... perhaps the # is breaking the substitution?  (Is it a reserved character?  Apologies if it is, but I missed it.)  It feels like the above should work - so that if we're exporting a comment of "Firstname Lastname" and an employeeID of "1234567" we should see a user in the password file on the *nix machine with a comment field of "Firstname Lastname,#1234567#" - but we weren't.  For the useradd we were seeing "Firstname Lastname,#{employeeID}#" and, as mentioned, the usermod was failing with a "no parameters" error.

Adam

**Comment by ryannewington** [comment]
Hi Adam,

You are correct in that a single attribute declaration can only be used inside an optional section.

What you will need to do is have multiple versions of the <command> element that use a 'rule' to determine which one should run, based on the presence of lack of presence of the employeeID and comment attributes.

You can see an example of rules and there usage in this [sample file](https://github.com/lithnet/ssh-managementagent/blob/master/src/Lithnet.SshMA/ConfigurationFiles/Solaris9/solaris9.xml)

It's a bit of a long way around, but it will do the job

Ryan

**Comment by aebenjam** [comment]
Actually, there were a couple different work-arounds that we found.  One was to do the concatenation (which is, essentially, what we were trying to do) using another attribute (which we flowed out and added to the MA schema.)  But, in the end, I found a more elegant solution that involved using a named match within a named match when reading the data for an import.  So now "comment" is the entire comment field, but employeeID is a subset of that same field.  Fortunately that worked and made for an elegant solution.  However, it was the least intuitive solution (at least, for me ;) ) and so it might have been nice had my first choice been an option.  (So... something for a future wish-list?)  Anyway, thanks for the proposed solution.  Let me know if you're interested in knowing more about how we implemented our solution as embedding some sort of employee identifier in the comment field (so we could do a join that is not tied to the *nix username) seemed an intuitive choice that others might want to leverage.

**Comment by ryannewington** [comment]
Hi Adam,

Glad you were able to find a solution for this. Doing the merge outside of the MA certainly makes life easier than what I proposed. I'm going to do a few updates to the code base soon, and I'll see if it's not too hard to implement the solution you were originally after.

Cheers

Ryan
