### ISSUE TITLE
abort command in Unix

### ISSUE THREAD

**Issue by juancarloscanto** [lithnet/ssh-managementagent#6]
Hi.

I use this Management Agent to create Oracle users in Unix servers. Instead of use unix command to create, modify or delete user, I create shell scripts that call to Oracle engina and execute Oracle commands to create, modify or delete Oracle Users.

My problem is: In some situations the script waits for inputo or confirmation after any error and I can not avoid this situation. Is it possible to configure any timeout in commands and after this time out, if the command didn't finish, kill the unix process and/or return an error code to MIM Synchronization?

Thanks in advanced
Kind regards

**Comment by ryannewington** [comment]
Hi @juancarloscanto,

async-commands are what you are after here. Have a look at the [sample config file](https://github.com/lithnet/ssh-managementagent/blob/master/src/Lithnet.SshMA/ConfigurationFiles/Kerberos/kerberos.xml) for using kadmin which operates in a similar way.

Have a look at the wiki page for [aync-command](https://github.com/lithnet/ssh-managementagent/wiki/async-command)

Let me know how you go

**Comment by juancarloscanto** [comment]
Thanks for your answer.

Just to confirm. Is it possible to combine an async-command and a command in the same object-operation in Full Import (I see a restriction in async-command referred to Import to FIM/MIM)?

Thanks
Kind regards

**Comment by ryannewington** [comment]
Yes, I believe so (sorry it's been a while since I wrote this MA). The restriction is that the async command can't be used to collect the actual objects for import. If the async command is responsible for creating the input that you need to parse, you would need to somehow pipe that output to a file, and use a synchronize command to read that file in using cat or something similar.

**Comment by juancarloscanto** [comment]
I will Try. Thanks a lot

Kind regards
